const actionTypes = {
  CREATE_ARTICLE_RATING_LOADING: ' CREATE_ARTICLE_RATING_LOADING',
  CREATE_ARTICLE_RATING_SUCCESS: 'CREATE_ARTICLE_RATING_SUCCESS',
  CREATE_ARTICLE_RATING_FAILURE: ' CREATE_ARTICLE_RATING_FAILURE',
  GET_USER_RATING_LOADING: ' GET_ARTICLE_RATING_LOADING',
  GET_USER_RATING_SUCCESS: 'GET_ARTICLE_RATING_SUCCESS',
  GET_USER_RATING_FAILURE: ' GET_ARTICLE_RATING_FAILURE'
};

export default actionTypes;
