const actionTypes = {
  COMMENT_LOADING: 'AUTH_LOADING',
  COMMENT_FETCHED: 'COMMENT_FETCHED',
  THREADS_FETCHED: 'THREADS_FETCHED',
  COMMENT_LIKED_FETCHED: 'COMMENT_LIKED_FETCHED'
};

export default actionTypes;
