const actionTypes = {
  COMMENT_LOADING: 'COMMENT_LOADING',
  COMMENT_FAILED: 'COMMENT_FAILED',
  COMMENT_FETCHED: 'COMMENT_FETCHED',
  THREADS_FETCHED: 'THREADS_FETCHED',
  UPDATE_COMMENT: 'UPDATE_COMMENT',
  COMMENT_LIKED_FETCHED: 'COMMENT_LIKED_FETCHED'
};

export default actionTypes;
