export default {
  IMAGE_LOADING: 'IMAGE_LOADING',
  STOP_IMAGE_LOADING: 'STOP_IMAGE_LOADING',
  DRAFT_LOADING: 'DRAFT_LOADING',
  PUBLISH_LOADING: 'PUBLISH_LOADING',
  PUBLISH_SUCCESS: 'PUBLISH_SUCCESS',
  PUBLISH_FAILURE: 'PUBLISH_FAILURE',
  SAVE_AS_DRAFT_SUCCESS: 'SAVE_AS_DRAFT_SUCCESS',
  SAVE_AS_DRAFT_FAILURE: 'SAVE_AS_DRAFT_FAILURE'
};
