export default {
  ARTICLE_LOADING: 'ARTICLE_LOADING',
  PUBLISH_SUCCESS: 'PUBLISH_SUCCESS',
  PUBLISH_FAILURE: 'PUBLISH_FAILURE',
  SAVE_AS_DRAFT_SUCCESS: 'SAVE_AS_DRAFT_SUCCESS',
  SAVE_AS_DRAFT_FAILURE: 'SAVE_AS_DRAFT_FAILURE'
};
