const actionTypes = {
  FETCH_USER_SUCCESS: 'FETCH_SUCCESS',
  FETCH_USER_FAILURE: 'FETCH_FAILURE',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',
  FETCH_USER_LOADING: 'FETCH_USER_LOADING',
  UPDATE_USER_LOADING: 'UPDATE_USER_LOADING',
  IS_AUTHENTICATED: 'IS_AUTHENTICATED',
  FETCH_CURRENT_USER_SUCCESS: 'FETCH_CURRENT_USER_SUCCESS',
  FETCH_CURRENT_USER_FAILURE: 'FETCH_CURRENT_USER_FAILURE',
  SET_IMAGE: 'SET_IMAGE',
  REMOVE_IMAGE: 'REMOVE_IMAGE'
};

export default actionTypes;
