const actionTypes = {
  FETCH_USER_SUCCESS: 'FETCH_SUCCESS',
  FETCH_USER_FAILURE: 'FETCH_FAILURE',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',
  FETCH_USER_LOADING: 'FETCH_USER_LOADING',
  UPDATE_USER_LOADING: 'UPDATE_USER_LOADING'
};

export default actionTypes;
