const actionTypes = {
  TOTAL_REACTIONS_LOADING: 'TOTAL_REACTIONS_LOADING',
  TOTAL_REACTIONS_SUCCESS: 'TOTAL_REACTIONS_SUCCESS',
  TOTAL_REACTIONS_FAILURE: 'TOTAL_REACTIONS_FAILURE',
  ARTICLE_REACTION_SUCCESS: 'ARTICLE_REACTION_SUCCESS'
};

export default actionTypes;
