const actionTypes = {
  TOTAL_REACTIONS_LOADING: 'TOTAL_REACTIONS_LOADING',
  TOTAL_REACTIONS_SUCCESS: 'TOTAL_REACTIONS_SUCCESS',
  TOTAL_REACTIONS_FAILURE: 'TOTAL_REACTIONS_FAILURE'
};

export default actionTypes;
