const actionTypes = {
  READ_ARTICLE_LOADING: 'READ_ARTICLE_LOADING',
  READ_ARTICLE_SUCCESS: 'READ_ARTICLE_SUCCESS',
  READ_ARTICLE_FAILURE: 'READ_ARTICLE_FAILURE',
  TOGGLE_ARTICLE_BOOKMARK: 'TOGGLE_ARTICLE_BOOKMARK'
};

export default actionTypes;
