const actionTypes = {
  FETCH_POPULAR_ARTICLES_SUCCESS: 'FETCH_POPULAR_ARTICLES_SUCCESS',
  FETCH_TRENDING_ARTICLES_SUCCESS: 'FETCH_TRENDING_ARTICLES_SUCCESS',
  FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
  FETCH_FEATURED_ARTICLES_SUCCESS: 'FETCH_FEATURED_ARTICLES_SUCCESS',
  FETCH_POPULAR_ARTICLES_FAILURE: 'FETCH_POPULAR_ARTICLES_FAILURE',
  FETCH_TRENDING_ARTICLES_FAILURE: 'FETCH_TRENDING_ARTICLES_FAILURE',
  FETCH_CATEGORIES_FAILURE: 'FETCH_CATEGORIES_FAILURE',
  FETCH_TAGS_SUCCESS: 'FETCH_TAGS_SUCCESS',
  FETCH_TAGS_FAILURE: 'FETCH_TAGS_FAILURE',
  FETCH_FEATURED_ARTICLES_FAILURE: 'FETCH_FEATURED_ARTICLES_FAILURE'
};

export default actionTypes;
