const actionTypes = {
  FETCH_POPULAR_ARTICLES: 'FETCH_POPULAR_ARTICLES',
  FETCH_TRENDING_ARTICLES: 'FETCH_TRENDING_ARTICLES',
  FETCH_CATEGORIES: 'FETCH_CATEGORIES',
  FETCH_TAGS: 'FETCH_TAGS',
  FETCH_FEATURED_ARTICLES: 'FETCH_FEATURED_ARTICLES',
  FETCH_POPULAR_ARTICLES_FAILURE: 'FETCH_POPULAR_ARTICLES_FAILURE',
  FETCH_TRENDING_ARTICLES_FAILURE: 'FETCH_TRENDING_ARTICLES',
  FETCH_CATEGORIES_FAILURE: 'FETCH_CATEGORIES',
  FETCH_TAGS_FAILURE: 'FETCH_TAGS',
  FETCH_FEATURED_ARTICLES_FAILURE: 'FETCH_FEATURED_ARTICLES',
};

export default actionTypes;
