const actionTypes = {

  AUTH_LOADING: 'AUTH_LOADING',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAILURE: 'SIGNUP_FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  SOCIAL_AUTH_SUCCESS: 'SOCIAL_AUTH_SUCCESS',
  SOCIAL_AUTH_FAIL: 'SOCIAL_AUTH_FAIL',
  READ_ARTICLE_LOADING: 'READ_ARTICLE_LOADING',
  READ_ARTICLE_SUCCESS: 'READ_ARTICLE_SUCCESS',
  READ_ARTICLE_FAILURE: 'READ_ARTICLE_FAILURE'
};

export default actionTypes;
